version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@6.3.0
  slack: circleci/slack@4.12.1

parameters:
  alerts-slack-channel:
    type: string
    default: manage_a_workforce_dev
  releases-slack-channel:
    type: string
    default: manage_a_workforce_dev

workflows:
  version: 2
  build-deploy-migration:
    jobs:
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_preprod
          filters:
            branches:
              only:
                - main
          env: "preprod"
          jira_update: true
          jira_env_type: production
          slack_notification: true
          slack_channel_name: << pipeline.parameters.releases-slack-channel >>
          requires:
            - build_docker
          context:
            - hmpps-common-vars
            - hmpps-wmt-migration-preprod
  security:
    triggers:
      - schedule:
          cron: "14 5 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/trivy_latest_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars