apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmpps-wmt-migration-cronjob
spec:
  schedule: {{ .Values.cronjob_schedule }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  timeZone: "Etc/UTC"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hmpps-wmt-migration
              image: quay.io/hmpps/hmpps-wmt-migration
              args:
                - /bin/bash
                - migrationRun.sh
{{ include "deployment.envs" . | nindent 14 }}
          restartPolicy: Never

